"""sprint_3_ai_integration

Revision ID: a3f02b9bac5b
Revises: be30ec0b9f04
Create Date: 2026-07-17 10:36:03.601049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database.base_class


# revision identifiers, used by Alembic.
revision: str = 'a3f02b9bac5b'
down_revision: Union[str, Sequence[str], None] = 'be30ec0b9f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_case_analyses',
    sa.Column('id', app.database.base_class.GUID(), nullable=False),
    sa.Column('case_id', app.database.base_class.GUID(), nullable=False),
    sa.Column('summary_draft', sa.Text(), nullable=False),
    sa.Column('summary_approved', sa.Text(), nullable=True),
    sa.Column('suggested_category', sa.String(length=100), nullable=False),
    sa.Column('suggested_severity', sa.String(length=50), nullable=False),
    sa.Column('suggested_priority', sa.String(length=10), nullable=False),
    sa.Column('suggested_department', sa.String(length=150), nullable=False),
    sa.Column('missing_information', sa.Text(), nullable=True),
    sa.Column('potential_duplicates', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by_id', app.database.base_class.GUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('model_provider', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('prompt_template_version', sa.String(length=50), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_hash', sa.String(length=100), nullable=True),
    sa.Column('response_hash', sa.String(length=100), nullable=True),
    sa.Column('model_confidence', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['officers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_legal_recommendations',
    sa.Column('id', app.database.base_class.GUID(), nullable=False),
    sa.Column('case_id', app.database.base_class.GUID(), nullable=False),
    sa.Column('suggested_sections', sa.Text(), nullable=False),
    sa.Column('officer_approved_sections', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by_id', app.database.base_class.GUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('model_provider', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('prompt_template_version', sa.String(length=50), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_hash', sa.String(length=100), nullable=True),
    sa.Column('response_hash', sa.String(length=100), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['officers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_fir_suggestions',
    sa.Column('id', app.database.base_class.GUID(), nullable=False),
    sa.Column('case_id', app.database.base_class.GUID(), nullable=False),
    sa.Column('fir_id', app.database.base_class.GUID(), nullable=False),
    sa.Column('original_narrative_draft', sa.Text(), nullable=False),
    sa.Column('approved_narrative', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by_id', app.database.base_class.GUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('model_provider', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('prompt_template_version', sa.String(length=50), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_hash', sa.String(length=100), nullable=True),
    sa.Column('response_hash', sa.String(length=100), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fir_id'], ['firs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['officers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_fir_suggestions')
    op.drop_table('ai_legal_recommendations')
    op.drop_table('ai_case_analyses')
    # ### end Alembic commands ###
