"""sprint_2_baseline

Revision ID: be30ec0b9f04
Revises: 
Create Date: 2026-07-17 10:20:55.559247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database.base_class


# revision identifiers, used by Alembic.
revision: str = 'be30ec0b9f04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizens',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('national_id', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', app.database.base_class.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('national_id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('officers',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('badge_number', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('lockout_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_password_change', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_by', app.database.base_class.GUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', app.database.base_class.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('badge_number'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('actor_id', app.database.base_class.GUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', app.database.base_class.GUID(), nullable=False),
    sa.Column('old_state', sa.String(length=4000), nullable=True),
    sa.Column('new_state', sa.String(length=4000), nullable=True),
    sa.Column('request_id', sa.String(length=50), nullable=True),
    sa.Column('correlation_id', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.database.base_class.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaints',
    sa.Column('citizen_id', app.database.base_class.GUID(), nullable=True),
    sa.Column('citizen_name', sa.String(length=100), nullable=False),
    sa.Column('citizen_contact', sa.String(length=20), nullable=False),
    sa.Column('complaint_text', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('assigned_officer_id', app.database.base_class.GUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', app.database.base_class.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['officers.id'], ),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_logs',
    sa.Column('officer_id', app.database.base_class.GUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.database.base_class.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('complaint_id', app.database.base_class.GUID(), nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_officer_id', app.database.base_class.GUID(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', app.database.base_class.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['officers.id'], ),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number'),
    sa.UniqueConstraint('complaint_id')
    )
    op.create_table('case_timeline_events',
    sa.Column('case_id', app.database.base_class.GUID(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', app.database.base_class.GUID(), nullable=True),
    sa.Column('evidence_id', app.database.base_class.GUID(), nullable=True),
    sa.Column('fir_id', app.database.base_class.GUID(), nullable=True),
    sa.Column('id', app.database.base_class.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['officers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidences',
    sa.Column('case_id', app.database.base_class.GUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', app.database.base_class.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firs',
    sa.Column('case_id', app.database.base_class.GUID(), nullable=False),
    sa.Column('fir_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('complainant_name', sa.String(length=100), nullable=False),
    sa.Column('complainant_contact', sa.String(length=20), nullable=False),
    sa.Column('incident_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('incident_place', sa.String(length=255), nullable=False),
    sa.Column('acts_sections', sa.String(length=500), nullable=False),
    sa.Column('details', sa.String(length=4000), nullable=False),
    sa.Column('created_by_id', app.database.base_class.GUID(), nullable=False),
    sa.Column('approved_by_id', app.database.base_class.GUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', app.database.base_class.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['officers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['officers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id'),
    sa.UniqueConstraint('fir_number')
    )
    op.create_table('evidence_versions',
    sa.Column('evidence_id', app.database.base_class.GUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('hash_algorithm', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by', app.database.base_class.GUID(), nullable=False),
    sa.Column('scan_status', sa.String(length=50), nullable=True),
    sa.Column('scan_engine', sa.String(length=100), nullable=True),
    sa.Column('scan_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gps_location', sa.String(length=100), nullable=True),
    sa.Column('device_model', sa.String(length=100), nullable=True),
    sa.Column('exif_present', sa.Boolean(), nullable=True),
    sa.Column('id', app.database.base_class.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['officers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fir_versions',
    sa.Column('fir_id', app.database.base_class.GUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('acts_sections', sa.String(length=500), nullable=False),
    sa.Column('details', sa.String(length=4000), nullable=False),
    sa.Column('modified_by_id', app.database.base_class.GUID(), nullable=False),
    sa.Column('id', app.database.base_class.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fir_id'], ['firs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modified_by_id'], ['officers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fir_versions')
    op.drop_table('evidence_versions')
    op.drop_table('firs')
    op.drop_table('evidences')
    op.drop_table('case_timeline_events')
    op.drop_table('cases')
    op.drop_table('login_logs')
    op.drop_table('complaints')
    op.drop_table('audit_logs')
    op.drop_table('officers')
    op.drop_table('citizens')
    # ### end Alembic commands ###
